//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraMouseSuite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CameraMouseSuite.ConsentResources", typeof(ConsentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 CMR10;}{\f1\fnil\fcharset0 CMTI10;}{\f2\fnil\fcharset2 Symbol;}}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\f0\fs20 The purpose of this form is to document that consent was obtained from a person over 18 years of age to participate in a research study. \par
        ///\i\f1\par
        ///\b Title of Research Study\b0 : \i0\f0 World-wide Collaboration to Empower People with Disabilities to Improve Assistive Interfaces.\par
        ///\par
        ///\b\i\f1 Inves [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdultRTF {
            get {
                return ResourceManager.GetString("AdultRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 CMR10;}{\f1\fnil\fcharset0 CMTI10;}{\f2\fswiss\fcharset0 Arial;}{\f3\fnil\fcharset2 Symbol;}}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\f0\fs20 The purpose of this form is to document that consent was obtained from a person between the ages of 7 and 18 to participate in a research study. If the minor cannot read this form, it must be read to him or her.\par
        ///\i\f1\par
        ///\b Title of Research Study\b0 : \i0\f0 World-wide Coll [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChildRTF {
            get {
                return ResourceManager.GetString("ChildRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 CMR10;}{\f1\fnil\fcharset0 CMTI10;}{\f2\fnil\fcharset2 Symbol;}}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\f0\fs20 The purpose of this form is to document that consent was obtained from a parent or guardian of a minor to participate in a research study. \par
        ///\i\f1\par
        ///\b Title of Research Study\b0 : \i0\f0 World-wide Collaboration to Empower People with Disabilities to Improve Assistive Interfaces.\par
        ///\par
        ///\b\i\f1 Inv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParentRTF {
            get {
                return ResourceManager.GetString("ParentRTF", resourceCulture);
            }
        }
    }
}
